import { useEffect, useMemo, useState } from "react";
import type { Artifacts } from "../lib/api";
import { api } from "../lib/api";
import { formatBytes } from "../lib/format";
import { Kpi, KpiGrid } from "../components/Kpi";

type ArtifactKind = {
  label: string;
  chip: string;
  dot: string;
};

function classifyArtifact(fileName: string): ArtifactKind {
  const lower = fileName.toLowerCase();
  if (/\.(ext[234]|btrfs|squashfs|wic|wic\.gz|wic\.bmap)$/.test(lower)) {
    const label = lower.split(".").pop() ?? "image";
    return { label, chip: "image", dot: "image" };
  }
  if (lower.includes("bzimage") || lower.includes("zimage") || lower.endsWith("uimage")) {
    return { label: "kernel", chip: "kernel", dot: "kernel" };
  }
  if (lower.includes("spdx")) {
    return { label: "SBOM", chip: "sbom", dot: "sbom" };
  }
  if (/\.(tar\.(gz|bz2|xz|zst)|tgz|zip)$/.test(lower)) {
    return { label: "archive", chip: "", dot: "archive" };
  }
  if (lower.endsWith(".manifest")) {
    return { label: "manifest", chip: "", dot: "" };
  }
  if (lower.endsWith(".json")) {
    return { label: "json", chip: "", dot: "" };
  }
  const extension = lower.includes(".") ? (lower.split(".").pop() ?? "file") : "file";
  return { label: extension, chip: "", dot: "" };
}

function architectureOf(packageName: string): string {
  const lower = packageName.toLowerCase();
  if (lower.endsWith(".rpm")) {
    const segments = packageName.slice(0, -4).split(".");
    return segments[segments.length - 1] || "noarch";
  }
  if (lower.endsWith(".deb") || lower.endsWith(".ipk")) {
    const segments = packageName.slice(0, -4).split("_");
    return segments[segments.length - 1] || "noarch";
  }
  return "noarch";
}

export default function Binaries() {
  const [artifacts, setArtifacts] = useState<Artifacts | null>(null);
  const [note, setNote] = useState("Scanning deploy directory…");
  const [busy, setBusy] = useState(false);
  const [filter, setFilter] = useState("");
  const [activeArch, setActiveArch] = useState("all");

  const load = async () => {
    setBusy(true);
    try {
      const result = await api.artifacts();
      setArtifacts(result);
      setNote("");
    } catch (error) {
      setNote(String((error as Error).message ?? error));
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    void load();
  }, []);

  const images = useMemo(() => {
    if (!artifacts) return [];
    return [...artifacts.images].sort((left, right) => right.bytes - left.bytes);
  }, [artifacts]);

  const architectureCounts = useMemo(() => {
    const counts = new Map<string, number>();
    for (const artifactPackage of artifacts?.packages ?? []) {
      const architecture = architectureOf(artifactPackage.name);
      counts.set(architecture, (counts.get(architecture) ?? 0) + 1);
    }
    return [...counts.entries()].sort((left, right) => right[1] - left[1]);
  }, [artifacts]);

  const packages = useMemo(() => {
    if (!artifacts) return [];
    const needle = filter.trim().toLowerCase();
    return artifacts.packages
      .filter((artifactPackage) => {
        if (activeArch !== "all" && architectureOf(artifactPackage.name) !== activeArch) return false;
        if (!needle) return true;
        return (
          artifactPackage.name.toLowerCase().includes(needle) ||
          artifactPackage.recipe.toLowerCase().includes(needle)
        );
      })
      .sort((left, right) => right.bytes - left.bytes);
  }, [artifacts, filter, activeArch]);

  const totalBytes = useMemo(() => {
    if (!artifacts) return 0;
    const imageBytes = artifacts.images.reduce((sum, image) => sum + image.bytes, 0);
    const packageBytes = artifacts.packages.reduce((sum, item) => sum + item.bytes, 0);
    return imageBytes + packageBytes;
  }, [artifacts]);

  const activeMachine = images[0]?.machine ?? "—";
  const isEmpty = artifacts && images.length === 0 && artifacts.packages.length === 0;

  return (
    <section className="page">
      <div className="page-head">
        <div className="head-lead">
          <div className="head-title">
            <h1>Binaries &amp; Deploy</h1>
            <span className="pill-tag">tmp/deploy</span>
          </div>
          <span className="head-desc">
            Target rootfs images, bootable kernel binaries, manifests, and package feeds generated by
            BitBake.
          </span>
        </div>
        <button className="build-cta" onClick={load} disabled={busy}>
          {busy ? "Scanning…" : "Rescan Deploy Dir"}
        </button>
      </div>

      {note && <p className="muted">{note}</p>}
      {isEmpty && (
        <p className="muted">No build artifacts found yet. Run a build to populate the deploy directory.</p>
      )}

      {artifacts && !isEmpty && (
        <>
          <KpiGrid>
            <Kpi
              label="Total artifacts size"
              value={formatBytes(totalBytes)}
              hint={`${images.length} deployable images`}
            />
            <Kpi
              label="Package feed"
              value={`${artifacts.packages.length.toLocaleString()} pkgs`}
              tone="accent"
              hint={`${architectureCounts.length} architectures`}
            />
            <Kpi label="Active machine" value={activeMachine} tone="cyan" />
            <Kpi label="Images generated" value={images.length.toLocaleString()} tone="emerald" />
          </KpiGrid>

          {images.length > 0 && (
            <>
              <div className="section-bar">
                <span className="section-title">Images &amp; Artifacts</span>
                <span className="section-meta">{images.length} files generated</span>
              </div>
              <table className="table">
                <thead>
                  <tr>
                    <th>Artifact name</th>
                    <th>Machine</th>
                    <th className="num">Size</th>
                  </tr>
                </thead>
                <tbody>
                  {images.map((image) => {
                    const kind = classifyArtifact(image.name);
                    return (
                      <tr key={`${image.machine}/${image.name}`}>
                        <td>
                          <span className="artifact-name">
                            <span className={`artifact-dot ${kind.dot}`} />
                            <span className="name">{image.name}</span>
                            <span className={`type-chip ${kind.chip}`}>{kind.label}</span>
                          </span>
                        </td>
                        <td className="muted small">{image.machine}</td>
                        <td className="num">{formatBytes(image.bytes)}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </>
          )}

          {artifacts.packages.length > 0 && (
            <>
              <div className="section-bar">
                <span className="section-title">Packages</span>
                <span className="section-meta">
                  {artifacts.packages.length.toLocaleString()} total
                </span>
              </div>
              <div className="arch-tabs">
                <button
                  className={`arch-tab ${activeArch === "all" ? "active" : ""}`}
                  onClick={() => setActiveArch("all")}
                >
                  All ({artifacts.packages.length.toLocaleString()})
                </button>
                {architectureCounts.map(([architecture, count]) => (
                  <button
                    key={architecture}
                    className={`arch-tab ${activeArch === architecture ? "active" : ""}`}
                    onClick={() => setActiveArch(architecture)}
                  >
                    {architecture} ({count.toLocaleString()})
                  </button>
                ))}
              </div>
              <div className="add-row">
                <input
                  placeholder="Filter by package or recipe name (e.g. gcc, kernel, openssl)…"
                  value={filter}
                  onChange={(event) => setFilter(event.target.value)}
                />
              </div>
              <table className="table">
                <thead>
                  <tr>
                    <th>Package</th>
                    <th>Recipe origin</th>
                    <th>Architecture</th>
                    <th className="num">Size</th>
                  </tr>
                </thead>
                <tbody>
                  {packages.map((artifactPackage) => (
                    <tr key={artifactPackage.name}>
                      <td>
                        <code>{artifactPackage.name}</code>
                      </td>
                      <td>
                        <span className="origin-link">{artifactPackage.recipe}</span>
                      </td>
                      <td>
                        <span className="arch-cell">{architectureOf(artifactPackage.name)}</span>
                      </td>
                      <td className="num">{formatBytes(artifactPackage.bytes)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              {packages.length === 0 && <p className="muted small">No packages match the filter.</p>}
            </>
          )}
        </>
      )}
    </section>
  );
}
