use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use rust_embed::RustEmbed;

use crate::core::workspace::FORGE_SOURCE_DIR;

pub const PLUGINS_DIR: &str = "plugins";
pub const ENTRYPOINT: &str = "metadata.py";

const HEADER: &str =
    "# Auto Generated by BitForge. Do not edit, changes won't last on the next iteration.";

#[derive(RustEmbed)]
#[folder = "src/core/plugins/scripts"]
struct PluginScripts;

pub fn names() -> Vec<String> {
    PluginScripts::iter()
        .filter(|file| file.ends_with(".py"))
        .map(|file| file.to_string())
        .collect()
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    let directory = root.join(FORGE_SOURCE_DIR).join(PLUGINS_DIR);
    fs::create_dir_all(&directory)
        .with_context(|| format!("failed to create {}", directory.display()))?;
    for file in PluginScripts::iter() {
        if !file.ends_with(".py") {
            continue;
        }
        let embedded = PluginScripts::get(&file)
            .with_context(|| format!("missing embedded plugin {file}"))?;
        let body = String::from_utf8_lossy(&embedded.data);
        let stamped = format!("{HEADER}\n{body}");
        let destination = directory.join(file.as_ref());
        fs::write(&destination, stamped)
            .with_context(|| format!("failed to write {}", destination.display()))?;
    }
    Ok(directory.join(ENTRYPOINT))
}
