use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::core::cli::{BitForgeConfig, LayerDependency, slug};
use crate::core::workspace::{FORGE_SOURCE_DIR, LAYERS_DIR};

pub const CONF_DIR: &str = "conf";
pub const LAYER_CONF_FILE: &str = "layer.conf";
pub const LOCAL_CONF_FILE: &str = "local.conf";
pub const BBLAYERS_CONF_FILE: &str = "bblayers.conf";

pub const GENERATED_HEADER: &str =
    "# Auto Generated by BitForge. Do not edit, changes won't last on the next iteration.";

fn strip_generated_header(contents: &str) -> &str {
    match contents.strip_prefix(GENERATED_HEADER) {
        Some(rest) => rest.strip_prefix('\n').unwrap_or(rest),
        None => contents,
    }
}

fn with_generated_header(contents: &str) -> String {
    format!("{GENERATED_HEADER}\n{}", strip_generated_header(contents))
}

pub fn write_generated_conf(dest: &Path, contents: &str) -> std::io::Result<()> {
    fs::write(dest, with_generated_header(contents))
}

pub fn copy_generated_conf(source: &Path, dest: &Path) -> std::io::Result<()> {
    let contents = fs::read_to_string(source)?;
    write_generated_conf(dest, &contents)
}

const TRACKING_INHERITS: [&str; 5] = [
    "rm_work",
    "buildhistory",
    "buildstats",
    "buildstats-summary",
    "image-buildinfo",
];

pub fn ensure_tracking_inherits(local_conf_path: &Path) -> std::io::Result<()> {
    let mut contents = fs::read_to_string(local_conf_path).unwrap_or_default();
    let mut additions = String::new();

    for class in TRACKING_INHERITS {
        if !class_inherited(&contents, class) {
            additions.push_str(&format!("INHERIT += \"{class}\"\n"));
        }
    }
    if !contents.contains("BUILDHISTORY_COMMIT") {
        additions.push_str("BUILDHISTORY_COMMIT = \"1\"\n");
    }

    if additions.is_empty() {
        return Ok(());
    }
    if !contents.is_empty() && !contents.ends_with('\n') {
        contents.push('\n');
    }
    contents.push_str("# BitForge status tracking (rm_work + build stats/history)\n");
    contents.push_str(&additions);
    fs::write(local_conf_path, contents)
}

fn class_inherited(contents: &str, class: &str) -> bool {
    contents.lines().any(|line| {
        let trimmed = line.trim_start();
        (trimmed.starts_with("INHERIT") || trimmed.starts_with("USER_CLASSES"))
            && trimmed.split_whitespace().any(|token| token.trim_matches('"') == class)
    })
}

pub fn effective_threads() -> usize {
    std::thread::available_parallelism()
        .map(|value| value.get())
        .unwrap_or(1)
        .saturating_sub(1)
        .max(1)
}

pub fn ensure_parallelism(local_conf_path: &Path) -> std::io::Result<()> {
    let effective = effective_threads();
    let mut contents = fs::read_to_string(local_conf_path).unwrap_or_default();
    let mut additions = String::new();
    if !key_present(&contents, "BB_NUMBER_THREADS") {
        additions.push_str(&format!("BB_NUMBER_THREADS ?= \"{effective}\"\n"));
    }
    if !key_present(&contents, "PARALLEL_MAKE") {
        additions.push_str(&format!("PARALLEL_MAKE ?= \"-j {effective}\"\n"));
    }
    if additions.is_empty() {
        return Ok(());
    }
    if !contents.is_empty() && !contents.ends_with('\n') {
        contents.push('\n');
    }
    contents.push_str("# BitForge auto parallelism (effective threads = CPUs - 1)\n");
    contents.push_str(&additions);
    fs::write(local_conf_path, contents)
}

fn key_present(contents: &str, key: &str) -> bool {
    contents.lines().any(|line| {
        let trimmed = line.trim_start();
        trimmed.starts_with(key) && trimmed[key.len()..].trim_start().starts_with(['?', '='])
    })
}

pub fn read_layer_priority(layer_dir: &Path) -> Option<u32> {
    let contents = fs::read_to_string(layer_dir.join(CONF_DIR).join(LAYER_CONF_FILE)).ok()?;
    contents.lines().find_map(|line| {
        let trimmed = line.trim();
        if trimmed.starts_with("BBFILE_PRIORITY_") {
            trimmed.split('"').nth(1).and_then(|value| value.trim().parse().ok())
        } else {
            None
        }
    })
}

const DEFAULT_MACHINE: &str = "qemux86-64";
const DEFAULT_DISTRO: &str = "nodistro";

pub fn write_layer_conf(
    layer_directory: &Path,
    layer_name: &str,
    priority: u32,
    compatible_release: &str,
) -> Result<()> {
    let conf_directory = layer_directory.join(CONF_DIR);
    fs::create_dir_all(&conf_directory)
        .with_context(|| format!("failed to create {}", conf_directory.display()))?;

    let contents = layer_conf_template(layer_name, priority, compatible_release);
    let conf_path = conf_directory.join(LAYER_CONF_FILE);
    write_generated_conf(&conf_path, &contents)
        .with_context(|| format!("failed to write {}", conf_path.display()))?;
    Ok(())
}

pub fn ensure_build_conf(root: &Path, config: &BitForgeConfig) -> Result<()> {
    let conf_directory = root.join(CONF_DIR);
    fs::create_dir_all(&conf_directory)
        .with_context(|| format!("failed to create {}", conf_directory.display()))?;

    write_local_conf(&conf_directory, config)?;
    write_bblayers_conf(root, config)?;
    Ok(())
}

pub fn write_bblayers_conf(root: &Path, config: &BitForgeConfig) -> Result<()> {
    let conf_directory = root.join(CONF_DIR);
    fs::create_dir_all(&conf_directory)
        .with_context(|| format!("failed to create {}", conf_directory.display()))?;
    let contents = bblayers_conf_template(config);
    let bblayers_path = conf_directory.join(BBLAYERS_CONF_FILE);
    write_generated_conf(&bblayers_path, &contents)
        .with_context(|| format!("failed to write {}", bblayers_path.display()))?;
    Ok(())
}

fn write_local_conf(conf_directory: &Path, _config: &BitForgeConfig) -> Result<()> {
    let local_conf_path = conf_directory.join(LOCAL_CONF_FILE);
    if local_conf_path.exists() {
        return Ok(());
    }
    fs::write(&local_conf_path, local_conf_template())
        .with_context(|| format!("failed to write {}", local_conf_path.display()))?;
    Ok(())
}

pub fn read_local_conf_value(root: &Path, key: &str) -> Option<String> {
    let path = root.join(CONF_DIR).join(LOCAL_CONF_FILE);
    let contents = fs::read_to_string(path).ok()?;
    for line in contents.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with(key) && trimmed[key.len()..].trim_start().starts_with(['?', '=']) {
            if let Some(position) = trimmed.find('=') {
                let value = trimmed[position + 1..].trim().trim_matches('"');
                return Some(value.to_string());
            }
        }
    }
    None
}

pub fn set_local_conf_value(root: &Path, key: &str, value: &str) -> Result<()> {
    let conf_directory = root.join(CONF_DIR);
    fs::create_dir_all(&conf_directory)?;
    let path = conf_directory.join(LOCAL_CONF_FILE);
    let existing = fs::read_to_string(&path).unwrap_or_default();

    let mut replaced = false;
    let mut lines: Vec<String> = existing
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            if !replaced && trimmed.starts_with(key) && trimmed[key.len()..].trim_start().starts_with(['?', '=']) {
                replaced = true;
                format!("{key} {} \"{value}\"", assignment_of(trimmed))
            } else {
                line.to_string()
            }
        })
        .collect();

    if !replaced {
        lines.push(format!("{key} ?= \"{value}\""));
    }

    let mut contents = lines.join("\n");
    contents.push('\n');
    fs::write(&path, contents).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

fn assignment_of(line: &str) -> &'static str {
    if line.contains("??=") {
        "??="
    } else if line.contains("?=") {
        "?="
    } else {
        "="
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct EnabledLayer {
    pub name: String,
    pub path: String,
    pub priority: Option<u32>,
    pub dependency: Option<String>,
    pub subpath: Option<String>,
    pub linked: bool,
}

pub fn enabled_layers(config: &BitForgeConfig) -> Vec<EnabledLayer> {
    let mut enabled = Vec::new();

    if config.workspace.is_some() {
        for layer in &config.layers {
            enabled.push(EnabledLayer {
                name: layer.name.clone(),
                path: layer.path.clone(),
                priority: Some(layer.priority),
                dependency: None,
                subpath: None,
                linked: true,
            });
        }
    } else if let Some(layer) = &config.layer {
        enabled.push(EnabledLayer {
            name: layer.name.clone(),
            path: ".".to_string(),
            priority: Some(layer.priority),
            dependency: None,
            subpath: None,
            linked: true,
        });
    }

    let release = config.effective_release();
    for (gitname, layers) in &config.dependency {
        let locations = resolve_layer_locations(gitname, layers, &release);
        for (layername, (_worktree_dir, layer_path)) in &locations {
            let name = Path::new(layer_path)
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            let identity = format!("{gitname}.{layername}");
            let linked = !config.is_disabled(layer_path)
                && !config.is_disabled(&identity)
                && !config.is_disabled(gitname);
            enabled.push(EnabledLayer {
                name,
                path: layer_path.clone(),
                priority: None,
                dependency: Some(gitname.clone()),
                subpath: Some(layername.clone()),
                linked,
            });
        }
    }

    let mut seen = std::collections::BTreeSet::new();
    enabled.retain(|layer| seen.insert(layer.path.clone()));
    enabled
}

pub(crate) fn base_ref_token(
    layers: &BTreeMap<String, LayerDependency>,
    effective_release: &str,
) -> String {
    let release_token = format!("b-{}", slug(effective_release));
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for layer in layers.values() {
        *counts.entry(layer.ref_token()).or_default() += 1;
    }
    let mut best: Option<(String, usize)> = None;
    for (token, count) in &counts {
        let is_better = match &best {
            None => true,
            Some((best_token, best_count)) => {
                if count != best_count {
                    count > best_count
                } else if (token == &release_token) != (best_token == &release_token) {
                    token == &release_token
                } else {
                    token < best_token
                }
            }
        };
        if is_better {
            best = Some((token.clone(), *count));
        }
    }
    best.map(|(token, _)| token).unwrap_or_default()
}

pub(crate) fn resolve_layer_locations(
    gitname: &str,
    layers: &BTreeMap<String, LayerDependency>,
    effective_release: &str,
) -> BTreeMap<String, (String, String)> {
    let base_path = format!("{FORGE_SOURCE_DIR}/{LAYERS_DIR}/{gitname}");
    let base_token = base_ref_token(layers, effective_release);
    let mut result = BTreeMap::new();
    for (layername, layer) in layers {
        let token = layer.ref_token();
        let worktree_dir = if token == base_token {
            base_path.clone()
        } else {
            format!("{base_path}/.forge/{token}")
        };
        let subpath = layer.subpath(layername);
        let layer_path = if subpath.is_empty() || subpath == gitname {
            worktree_dir.clone()
        } else {
            format!("{worktree_dir}/{subpath}")
        };
        result.insert(layername.clone(), (worktree_dir, layer_path));
    }
    result
}

fn layer_paths(config: &BitForgeConfig) -> Vec<String> {
    enabled_layers(config)
        .into_iter()
        .filter(|layer| layer.linked)
        .map(|layer| format!("${{TOPDIR}}/../{}", layer.path))
        .collect()
}

fn layer_conf_template(layer_name: &str, priority: u32, compatible_release: &str) -> String {
    format!(
        "BBPATH .= \":${{LAYERDIR}}\"\n\
BBFILES += \"${{LAYERDIR}}/recipes-*/*/*.bb ${{LAYERDIR}}/recipes-*/*/*.bbappend\"\n\
BBFILE_COLLECTIONS += \"{layer_name}\"\n\
BBFILE_PATTERN_{layer_name} = \"^${{LAYERDIR}}/\"\n\
BBFILE_PRIORITY_{layer_name} = \"{priority}\"\n\
LAYERDEPENDS_{layer_name} = \"core\"\n\
LAYERSERIES_COMPAT_{layer_name} = \"{compatible_release}\"\n"
    )
}

fn local_conf_template() -> String {
    format!(
        "MACHINE ??= \"{DEFAULT_MACHINE}\"\n\
DISTRO ?= \"{DEFAULT_DISTRO}\"\n\
PACKAGE_CLASSES ?= \"package_rpm\"\n\
USER_CLASSES ?= \"buildstats\"\n\
PATCHRESOLVE = \"noop\"\n\
CONF_VERSION = \"2\"\n"
    )
}

fn bblayers_conf_template(config: &BitForgeConfig) -> String {
    let entries = layer_paths(config)
        .into_iter()
        .map(|path| format!("  {path} \\\n"))
        .collect::<String>();
    format!(
        "POKY_BBLAYERS_CONF_VERSION = \"2\"\n\
BBPATH = \"${{TOPDIR}}\"\n\
BBFILES ?= \"\"\n\
BBLAYERS ?= \" \\\n{entries}\"\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enabled_layers_match_build_configuration() {
        let config: BitForgeConfig = toml::from_str(
            r#"
[workspace]
name = "test"
yocto_release = "scarthgap"
[[layers]]
name = "meta-project"
path = "layers/meta-project"
priority = 6
[dependency.repo.meta-oe]
giturl = "https://example.org/repo"
branch = "scarthgap"
[dependency.repo.custom-bsp]
giturl = "https://example.org/repo"
branch = "scarthgap"
path = "vendor/meta-custom-bsp"
[dependency.repo.pinned]
giturl = "https://example.org/repo"
commit = "abcdef1234567890"
path = "meta-net"
"#,
        )
        .unwrap();
        let layers = enabled_layers(&config);
        assert_eq!(layers.len(), 4);
        assert_eq!(layers[0].dependency, None);
        assert_eq!(layers[1].path, "ForgeSource/layers/repo/vendor/meta-custom-bsp");
        assert_eq!(layers[1].name, "meta-custom-bsp");
        assert_eq!(layers[2].path, "ForgeSource/layers/repo/meta-oe");
        assert_eq!(
            layers[3].path,
            "ForgeSource/layers/repo/.forge/c-abcdef123456/meta-net"
        );
        assert_eq!(layers[3].name, "meta-net");
        let configuration = bblayers_conf_template(&config);
        for layer in layers {
            let entry = format!("${{TOPDIR}}/../{} \\\n", layer.path);
            assert_eq!(configuration.matches(&entry).count(), 1);
        }
    }
}
